name: 🐛 Bug Report
description: Report a bug or issue with the Oracle Telegram bot
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Example: When I click 'Active Tasks', the bot returns an error instead of showing my tasks."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to main menu
        2. Click on 'Tasks'
        3. Click on 'Active Tasks'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected to see my list of active tasks."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "The bot showed an error message: 'Internal server error'"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Bot Version
      description: Which version of the bot are you using? (Type /start in the bot to check)
      placeholder: "v1.0.0"
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language are you using in the bot?
      options:
        - English
        - Ukrainian
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This happens only when I'm using the bot on mobile."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
