name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Oracle Telegram bot
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input to make Oracle better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when... OR It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to have a button that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Another way to solve this could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the bot does this feature relate to?
      options:
        - Tasks Management
        - Statistics/Reports
        - Navigation/UI
        - Admin Features
        - Notifications
        - Localization
        - Other
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        Example: "As a field worker, I would use this feature to quickly filter tasks by priority so I can focus on urgent issues first."
    validations:
      required: false

  - type: textarea
    id: mockup
    attributes:
      label: Mockup/Example
      description: If you have a mockup, screenshot, or example from another app, please share it here
      placeholder: Drag and drop images here or describe the UI flow

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request
      placeholder: "This feature is similar to what [other app] does..."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: This feature would benefit other users, not just me
          required: false
